<?php
/**
 * This file contains the class DepartmentTaxonomy, this class is responsible for registering the Department taxonomy.
 *
 * @namespace KSPlugin
 */

namespace KSPlugin;

/**
 * Class DepartmentTaxonomy
 */
class DepartmentTaxonomy
{

    /**
     * Department constructor.
     */
    public function __construct()
    {
        \add_action('init', [ $this, 'registerTaxonomy' ], 0);
        \add_action('acf/include_fields', [ $this, 'registerACFFields' ]);
    }

    /**
     * Register Department taxonomy
     * @return void
     */
    public function registerTaxonomy(): void
    {

        $labels = [
            'name'                       => _x('Departments', 'Taxonomy General Name', 'KS-plugin'),
            'singular_name'              => _x('Department', 'Taxonomy Singular Name', 'KS-plugin'),
            'menu_name'                  => __('Departments', 'KS-plugin'),
            'all_items'                  => __('All Departments', 'KS-plugin'),
            'parent_item'                => __('Parent Department', 'KS-plugin'),
            'parent_item_colon'          => __('Parent Department:', 'KS-plugin'),
            'new_item_name'              => __('New Department', 'KS-plugin'),
            'add_new_item'               => __('Add New Department', 'KS-plugin'),
            'edit_item'                  => __('Edit Department', 'KS-plugin'),
            'update_item'                => __('Update Department', 'KS-plugin'),
            'view_item'                  => __('View Department', 'KS-plugin'),
            'separate_items_with_commas' => __(
                'Separate Departments with commas',
                'KS-plugin'
            ),
            'add_or_remove_items'        => __('Add or remove Departments', 'KS-plugin'),
            'choose_from_most_used'      => __(
                'Choose from the most used Departments',
                'inussuk'
            ),
            'popular_items'              => __('Popular Departments', 'KS-plugin'),
            'search_items'               => __('Search Departments', 'KS-plugin'),
            'not_found'                  => __('No Departments Found', 'KS-plugin'),
            'no_terms'                   => __('No Departments', 'KS-plugin'),
            'items_list'                 => __('Departments list', 'KS-plugin'),
            'items_list_navigation'      => __('Departments list navigation', 'KS-plugin'),
        ];

        $rewrite = [
            'slug'         => 'department',
            'with_front'   => true,
            'hierarchical' => false,
        ];

        $args = [
            'labels'            => $labels,
            'hierarchical'      => true,
            'public'            => true,
            'show_ui'           => true,
            'show_admin_column' => true,
            'show_in_nav_menus' => true,
            'show_tagcloud'     => true,
            'rewrite'           => $rewrite,
            'show_in_rest'      => true,
        ];

        \register_taxonomy(
            'department',
            [
				'page',
	            'post',
	            'hearing-response',
	            'public-hearing',
	            'question-answer',
	            'offering'
            ],
            $args
        );
    }

    /**
     * Register ACF fields for Department taxonomy
     * @return void
     */
    public function registerACFFields(): void
    {

        if (! function_exists('acf_add_local_field_group')) {
            return;
        }

        \acf_add_local_field_group(array(
            'key'                   => 'group_602169c88c6ca',
            'title'                 => __('Department','KS-plugin'),
            'fields'                => array(
                array(
                    'key'               => 'field_60216dbc53be0',
                    'label'             => __('Former URL', 'KS-plugin'),
                    'name'              => '_former_url',
                    'aria-label'        => '',
                    'type'              => 'url',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'translations'      => 'ignore',
                ),
                array(
                    'key'               => 'field_602169f8b6701',
                    'label'             => __('Phone number', 'KS-plugin'),
                    'name'              => 'phonenumber',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => __('Phone Instructions', 'KS-plugin'),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => __('Phone placeholder', 'KS-plugin'),
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                    'translations'      => 'sync',
                ),
                array(
                    'key'               => 'field_60216a3bb6702',
                    'label'             => __('Email', 'KS-plugin'),
                    'name'              => 'email',
                    'aria-label'        => '',
                    'type'              => 'email',
                    'instructions'      => '',
                    'required'          => 1,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'translations'      => 'sync',
                ),
                array(
                    'key'               => 'field_6025693ac85d3',
                    'label'             => __('PO Box', 'KS-plugin'),
                    'name'              => 'po_box',
                    'aria-label'        => '',
                    'type'              => 'number',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => __('PO Box - default value', 'KS-plugin'),
                    'placeholder'       => 1005,
                    'prepend'           => '',
                    'append'            => '',
                    'min'               => '',
                    'max'               => '',
                    'step'              => '',
                    'translations'      => 'sync',
                ),
                array(
                    'key'               => 'field_60216a5db6703',
                    'label'             => __('Address line 1', 'KS-plugin'),
                    'name'              => 'address_line_1',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => __('Address line 1 - instructions', 'KS-plugin'),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => __('Address Placeholder', 'KS-plugin'),
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                    'translations'      => 'sync',
                ),
                array(
                    'key'               => 'field_60216a69b6704',
                    'label'             => __('Address line 2', 'KS-plugin'),
                    'name'              => 'address_line_2',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                    'translations'      => 'sync',
                ),
                array(
                    'key'               => 'field_60216a7ba3734',
                    'label'             => __('Postcode', 'KS-plugin'),
                    'name'              => 'zipcode',
                    'aria-label'        => '',
                    'type'              => 'number',
                    'instructions'      => __('Postcode - instructions', 'KS-plugin'),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => __('Postcode - placeholder', 'KS-plugin'),
                    'prepend'           => '',
                    'append'            => '',
                    'min'               => '',
                    'max'               => '',
                    'step'              => '',
                    'translations'      => 'sync',
                ),
                array(
                    'key'               => 'field_60216aa0a3735',
                    'label'             => __('City', 'KS-plugin'),
                    'name'              => 'city',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => __('City - instructions', 'KS-plugin'),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => __('City - placeholder', 'KS-plugin'),
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                    'translations'      => 'sync',
                ),
                array(
                    'key'               => 'field_602558eac4b23',
                    'label'             => __('Standard opening hours', 'KS-plugin'),
                    'name'              => 'standard_opening_hours',
                    'aria-label'        => '',
                    'type'              => 'true_false',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'message'           => '',
                    'default_value'     => 1,
                    'ui'                => 1,
                    'ui_on_text'        => 'Standard',
                    'ui_off_text'       => 'Custom',
                    'translations'      => 'sync',
                ),
                array(
                    'key'               => 'field_60216acaa3736',
                    'label'             =>  __('Opening hours', 'KS-plugin'),
                    'name'              => 'opening_hours',
                    'aria-label'        => '',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field'    => 'field_602558eac4b23',
                                'operator' => '!=',
                                'value'    => '1',
                            ),
                        ),
                    ),
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => __('Add days', 'KS-plugin'),
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_60216afba3737',
                            'label'             => __('Days', 'KS-plugin'),
                            'name'              => 'days',
                            'aria-label'        => '',
                            'type'              => 'select',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'choices'           => array(
                                1 => __('Monday', 'KS-plugin'),
                                2 => __('Tuesday', 'KS-plugin'),
                                3 => __('Wednesday', 'KS-plugin'),
                                4 => __('Thursday', 'KS-plugin'),
                                5 => __('Friday', 'KS-plugin'),
                                6 => __('Saturday', 'KS-plugin'),
                                7 => __('Sunday', 'KS-plugin'),
                            ),
                            'default_value'     => array(),
                            'allow_null'        => 0,
                            'multiple'          => 1,
                            'ui'                => 1,
                            'ajax'              => 0,
                            'return_format'     => 'value',
                            'translations'      => 'sync',
                            'placeholder'       => '',
                            'parent_repeater'   => 'field_60216acaa3736',
                        ),
                        array(
                            'key'               => 'field_60216b63a3739',
                            'label'             => __('Opens', 'KS-plugin'),
                            'name'              => 'opens',
                            'aria-label'        => '',
                            'type'              => 'number',
                            'instructions'      => __('Opens - instructions', 'KS-plugin'),
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'min'               => '',
                            'max'               => '',
                            'step'              => '',
                            'translations'      => 'sync',
                            'parent_repeater'   => 'field_60216acaa3736',
                        ),
                        array(
                            'key'               => 'field_60216beea373a',
                            'label'             => __('Closes', 'KS-plugin'),
                            'name'              => 'closes',
                            'aria-label'        => '',
                            'type'              => 'number',
                            'instructions'      => __('Closes - instructions', 'KS-plugin'),
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'min'               => '',
                            'max'               => '',
                            'step'              => '',
                            'translations'      => 'sync',
                            'parent_repeater'   => 'field_60216acaa3736',
                        ),
                    ),
                    'rows_per_page'     => 20,
                ),
                array(
                    'key'               => 'field_60216c02a373b',
                    'label'             => __('Phone hours', 'KS-plugin'),
                    'name'              => 'phone_hours',
                    'aria-label'        => '',
                    'type'              => 'repeater',
                    'instructions'      => __('Phone hours - instructions', 'KS-plugin'),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => __('Add days', 'KS-plugin'),
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_60216c02a373c',
                            'label'             => __('Days', 'KS-plugin'),
                            'name'              => 'days',
                            'aria-label'        => '',
                            'type'              => 'select',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'choices'           => array(
	                            1 => __('Monday', 'KS-plugin'),
	                            2 => __('Tuesday', 'KS-plugin'),
	                            3 => __('Wednesday', 'KS-plugin'),
	                            4 => __('Thursday', 'KS-plugin'),
	                            5 => __('Friday', 'KS-plugin'),
	                            6 => __('Saturday', 'KS-plugin'),
	                            7 => __('Sunday', 'KS-plugin'),
                            ),
                            'default_value'     => array(),
                            'allow_null'        => 0,
                            'multiple'          => 1,
                            'ui'                => 1,
                            'ajax'              => 0,
                            'return_format'     => 'value',
                            'translations'      => 'sync',
                            'placeholder'       => '',
                            'parent_repeater'   => 'field_60216c02a373b',
                        ),
                        array(
                            'key'               => 'field_60216c02a373d',
                            'label'             => __('Opens', 'KS-plugin'),
                            'name'              => 'opens',
                            'aria-label'        => '',
                            'type'              => 'number',
                            'instructions'      => __('Opens - instructions', 'KS-plugin'),
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'min'               => '',
                            'max'               => '',
                            'step'              => '',
                            'translations'      => 'sync',
                            'parent_repeater'   => 'field_60216c02a373b',
                        ),
                        array(
                            'key'               => 'field_60216c02a373e',
                            'label'             => __('Closes', 'KS-plugin'),
                            'name'              => 'closes',
                            'aria-label'        => '',
                            'type'              => 'number',
                            'instructions'      => __('Closes - instructions', 'KS-plugin'),
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'min'               => '',
                            'max'               => '',
                            'step'              => '',
                            'translations'      => 'sync',
                            'parent_repeater'   => 'field_60216c02a373b',
                        ),
                    ),
                    'rows_per_page'     => 20,
                ),
                array(
                    'key'               => 'field_60649f1a0eebe',
                    'label'             => __('Ignore holiday closing', 'KS-plugin'),
                    'name'              => 'ignore_holiday_closing',
                    'aria-label'        => '',
                    'type'              => 'true_false',
                    'instructions'      => __('Ignore holiday closing - instructions', 'KS-plugin'),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'message'           => '',
                    'default_value'     => 0,
                    'ui'                => 0,
                    'translations'      => 'sync',
                    'ui_on_text'        => '',
                    'ui_off_text'       => '',
                ),
                array(
                    'key'               => 'field_60216c15a373f',
                    'label'             => __('Requires appointment', 'KS-plugin'),
                    'name'              => 'requires_appointment',
                    'aria-label'        => '',
                    'type'              => 'true_false',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'message'           => '',
                    'default_value'     => 0,
                    'ui'                => 0,
                    'translations'      => 'sync',
                    'ui_on_text'        => '',
                    'ui_off_text'       => '',
                ),
                array(
                    'key'               => 'field_60216c30a3740',
                    'label'             => __('GLN', 'KS-plugin'),
                    'name'              => 'gln',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                    'translations'      => 'sync',
                ),
                array(
                    'key'               => 'field_603edb1fbcfd8',
                    'label'             => 'Color',
                    'name'              => 'color',
                    'aria-label'        => '',
                    'type'              => 'select',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'choices'           => array(
                        'bg-transparent'                => __('No color', 'KS-plugin'),
                        'bg-brand-blue text-white'      => __('Blue', 'KS-plugin'),
                        'bg-brand-purple text-white'    => __('Purple', 'KS-plugin'),
                        'bg-brand-green text-white'     => __('Green', 'KS-plugin'),
                        'bg-brand-red text-white'       => __('Red', 'KS-plugin'),
                        'bg-brand-orange text-white'    => __('Orange', 'KS-plugin'),
                        'bg-brand-lightblue text-white' => __('Light Blue', 'KS-plugin'),
                    ),
                    'default_value'     => 'bg-transparent',
                    'allow_null'        => 0,
                    'multiple'          => 0,
                    'ui'                => 0,
                    'return_format'     => 'value',
                    'translations'      => 'sync',
                    'ajax'              => 0,
                    'placeholder'       => '',
                ),
                array(
                    'key'               => 'field_604a3be61d60a',
                    'label'             => __('Social', 'KS-plugin'),
                    'name'              => 'social',
                    'aria-label'        => '',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => __('Add link', 'KS-plugin'),
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_604a3c211d60b',
                            'label'             => __('Link', 'KS-plugin'),
                            'name'              => 'link',
                            'aria-label'        => '',
                            'type'              => 'url',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'translations'      => 'sync',
                            'parent_repeater'   => 'field_604a3be61d60a',
                        ),
                        array(
                            'key'               => 'field_604a3c3a1d60c',
                            'label'             => __('Label', 'KS-plugin'),
                            'name'              => 'label',
                            'aria-label'        => '',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                            'translations'      => 'sync',
                            'parent_repeater'   => 'field_604a3be61d60a',
                        ),
                    ),
                    'rows_per_page'     => 20,
                ),
            ),
            'location'              => array(
                array(
                    array(
                        'param'    => 'taxonomy',
                        'operator' => '==',
                        'value'    => 'department',
                    ),
                ),
            ),
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'left',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
            'show_in_rest'          => false,
        ));
    }
}
